version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/output:/app/output
      - ../backend:/backend

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    volumes:
      - ../frontend:/frontend:delegated
      - /frontend/node_modules

volumes:
  uploads:
  output:
